/* ============================================================================
   Seed du référentiel PAYS (ref_pays) — codes + désignations (245 pays).
   Source : fichier « PAYS AVEC LEUR CODE ». Base : npg_gestion_caisse (SQL Server).
   Idempotent : ninsère que les codes pays encore absents.
   ============================================================================ */
SET NOCOUNT ON;

;WITH src(code, libelle) AS (
    SELECT * FROM (VALUES
        (N'AD', N'Andorre'),
        (N'AE', N'Emir.arab.unis'),
        (N'AF', N'Afghanistan'),
        (N'AG', N'Antigua/Barbuda'),
        (N'AI', N'Anguilla'),
        (N'AL', N'Albanie'),
        (N'AM', N'Arménie'),
        (N'AN', N'Antilles néerl.'),
        (N'AO', N'Angola'),
        (N'AQ', N'Antarctique'),
        (N'AR', N'Argentine'),
        (N'AS', N'Samoa, améric.'),
        (N'AT', N'Autriche'),
        (N'AU', N'Australie'),
        (N'AW', N'Aruba'),
        (N'AZ', N'Azerbaïdjan'),
        (N'BA', N'Bosnie-Herz.'),
        (N'BB', N'Barbade'),
        (N'BD', N'Bangladesh'),
        (N'BE', N'Belgique'),
        (N'BF', N'Burkina Faso'),
        (N'BG', N'Bulgarie'),
        (N'BH', N'Bahreïn'),
        (N'BI', N'Burundi'),
        (N'BJ', N'Bénin'),
        (N'BL', N'Blue'),
        (N'BM', N'Bermudes'),
        (N'BN', N'Brunéi Daruss.'),
        (N'BO', N'Bolivie'),
        (N'BR', N'Brésil'),
        (N'BS', N'Bahamas'),
        (N'BT', N'Bhoutan'),
        (N'BV', N'Ile Bouvet'),
        (N'BW', N'Botswana'),
        (N'BY', N'Biélorussie'),
        (N'BZ', N'Bélize'),
        (N'CA', N'Canada'),
        (N'CC', N'Iles Cocos'),
        (N'CD', N'Rép. dém. Congo'),
        (N'CF', N'Rép. centrafr.'),
        (N'CG', N'Congo'),
        (N'CH', N'Suisse'),
        (N'CI', N'Côte d''Ivoire'),
        (N'CK', N'Iles Cook'),
        (N'CL', N'Chili'),
        (N'CM', N'Cameroun'),
        (N'CN', N'Chine'),
        (N'CO', N'Colombie'),
        (N'CR', N'Costa Rica'),
        (N'CS', N'Serbie/Montén.'),
        (N'CU', N'Cuba'),
        (N'CV', N'Cap-Vert'),
        (N'CX', N'Ile Christmas'),
        (N'CY', N'Chypre'),
        (N'CZ', N'Rép. tchèque'),
        (N'DE', N'Allemagne'),
        (N'DJ', N'Djibouti'),
        (N'DK', N'Danemark'),
        (N'DM', N'Dominique'),
        (N'DO', N'Rép.Dominicaine'),
        (N'DZ', N'Algérie'),
        (N'EC', N'Equateur'),
        (N'EE', N'Estonie'),
        (N'EG', N'Egypte'),
        (N'EH', N'Sahara occ.'),
        (N'ER', N'Erythrée'),
        (N'ES', N'Espagne'),
        (N'ET', N'Ethiopie'),
        (N'EU', N'Union Europ.'),
        (N'FI', N'Finlande'),
        (N'FJ', N'Fidji'),
        (N'FK', N'Malouines'),
        (N'FM', N'Micronésie'),
        (N'FO', N'Féroé, Iles'),
        (N'FR', N'France'),
        (N'GA', N'Gabon'),
        (N'GB', N'Royaume-Uni'),
        (N'GD', N'Grenade'),
        (N'GE', N'Géorgie'),
        (N'GF', N'Guyane franç.'),
        (N'GH', N'Ghana'),
        (N'GI', N'Gibraltar'),
        (N'GL', N'Groenland'),
        (N'GM', N'Gambie'),
        (N'GN', N'Guinée'),
        (N'GP', N'Guadeloupe'),
        (N'GQ', N'Guinée équator.'),
        (N'GR', N'Grèce'),
        (N'GS', N'Iles Sandw. Sud'),
        (N'GT', N'Guatemala'),
        (N'GU', N'Guam'),
        (N'GW', N'Guinée-Bissau'),
        (N'GY', N'Rép.coop.Guyana'),
        (N'HK', N'Hong Kong'),
        (N'HM', N'Il.Heard/McDon.'),
        (N'HN', N'Honduras'),
        (N'HR', N'Croatie'),
        (N'HT', N'Haïti'),
        (N'HU', N'Hongrie'),
        (N'ID', N'Indonésie'),
        (N'IE', N'Irlande'),
        (N'IL', N'Israël'),
        (N'IN', N'Inde'),
        (N'IO', N'TerBritOcéanInd'),
        (N'IQ', N'Iraq'),
        (N'IR', N'Iran'),
        (N'IS', N'Islande'),
        (N'IT', N'Italie'),
        (N'JM', N'Jamaïque'),
        (N'JO', N'Jordanie'),
        (N'JP', N'Japon'),
        (N'KE', N'Kenya'),
        (N'KG', N'Kirghizistan'),
        (N'KH', N'Cambodge'),
        (N'KI', N'Kiribati'),
        (N'KM', N'Comores'),
        (N'KN', N'St Chr.& Niévès'),
        (N'KP', N'RépDémPopCorée'),
        (N'KR', N'Corée du Sud'),
        (N'KW', N'Koweït'),
        (N'KY', N'Iles Caïmans'),
        (N'KZ', N'Kazakhstan'),
        (N'LA', N'Laos'),
        (N'LB', N'Liban'),
        (N'LC', N'Sainte-Lucie'),
        (N'LI', N'Liechtenstein'),
        (N'LK', N'Sri Lanka'),
        (N'LR', N'Liberia'),
        (N'LS', N'Lesotho'),
        (N'LT', N'Lituanie'),
        (N'LU', N'Luxembourg'),
        (N'LV', N'Lettonie'),
        (N'LY', N'Libye'),
        (N'MA', N'Maroc'),
        (N'MC', N'Monaco'),
        (N'MD', N'Moldavie'),
        (N'MG', N'Madagascar'),
        (N'MH', N'Iles Marshall'),
        (N'MK', N'Macédoine'),
        (N'ML', N'Mali'),
        (N'MM', N'Myanmar'),
        (N'MN', N'Mongolie'),
        (N'MO', N'Macao'),
        (N'MP', N'Iles Mariannes'),
        (N'MQ', N'Martinique'),
        (N'MR', N'Mauritanie'),
        (N'MS', N'Montserrat'),
        (N'MT', N'Malte'),
        (N'MU', N'Ile Maurice'),
        (N'MV', N'Maldives'),
        (N'MW', N'Malawi'),
        (N'MX', N'Mexique'),
        (N'MY', N'Malaisie'),
        (N'MZ', N'Mozambique'),
        (N'NC', N'Nvlle Calédonie'),
        (N'NE', N'Niger'),
        (N'NF', N'Ile Norfolk'),
        (N'NG', N'Nigeria'),
        (N'NI', N'Nicaragua'),
        (N'NL', N'Pays-Bas'),
        (N'NO', N'Norvège'),
        (N'NP', N'Népal'),
        (N'NR', N'Nauru'),
        (N'NT', N'OTAN'),
        (N'NU', N'Niue'),
        (N'NZ', N'Nvelle Zélande'),
        (N'OM', N'Oman'),
        (N'OR', N'Orange'),
        (N'PA', N'Panama'),
        (N'PE', N'Pérou'),
        (N'PF', N'Polynésie fran.'),
        (N'PG', N'Pap.Nouv.Guinée'),
        (N'PH', N'Philippines'),
        (N'PK', N'Pakistan'),
        (N'PL', N'Pologne'),
        (N'PM', N'StPierre & Miq.'),
        (N'PN', N'Iles Pitcairn'),
        (N'PR', N'Porto Rico'),
        (N'PS', N'Palestine'),
        (N'PT', N'Portugal'),
        (N'PW', N'Palau'),
        (N'PY', N'Paraguay'),
        (N'QA', N'Qatar'),
        (N'RE', N'Réunion'),
        (N'RO', N'Roumanie'),
        (N'RU', N'Féd. de Russie'),
        (N'RW', N'Rwanda'),
        (N'SA', N'Arabie Saoudite'),
        (N'SB', N'Iles Salomon'),
        (N'SC', N'Seychelles'),
        (N'SD', N'Soudan'),
        (N'SE', N'Suède'),
        (N'SG', N'Singapour'),
        (N'SH', N'Sainte-Hélène'),
        (N'SI', N'Slovénie'),
        (N'SJ', N'Iles Svalbard'),
        (N'SK', N'Slovaquie'),
        (N'SL', N'Sierra Leone'),
        (N'SM', N'Saint-Marin'),
        (N'SN', N'Sénégal'),
        (N'SO', N'Somalie'),
        (N'SR', N'Suriname'),
        (N'ST', N'São Tomé-et-Pr.'),
        (N'SV', N'El Salvador'),
        (N'SY', N'Syrie'),
        (N'SZ', N'Swaziland'),
        (N'TC', N'Turks & Caicos'),
        (N'TD', N'Tchad'),
        (N'TF', N'TOM'),
        (N'TG', N'Togo'),
        (N'TH', N'Thaïlande'),
        (N'TJ', N'Tadjikistan'),
        (N'TK', N'Iles Tokelau'),
        (N'TL', N'Timor oriental'),
        (N'TM', N'Turkménistan'),
        (N'TN', N'Tunisie'),
        (N'TO', N'Tonga'),
        (N'TP', N'Timor oriental'),
        (N'TR', N'Turquie'),
        (N'TT', N'Trinité &Tobago'),
        (N'TV', N'Tuvalu'),
        (N'TW', N'Taïwan'),
        (N'TZ', N'Tanzanie'),
        (N'UA', N'Ukraine'),
        (N'UG', N'Ouganda'),
        (N'UM', N'Iles Minor Outl'),
        (N'UN', N'Nations Unies'),
        (N'US', N'Etats-Unis'),
        (N'UY', N'Uruguay'),
        (N'UZ', N'Ouzbékistan'),
        (N'VA', N'Vatican'),
        (N'VC', N'Saint Vincent'),
        (N'VE', N'Venezuela'),
        (N'VG', N'I. vierges brit'),
        (N'VI', N'I. vierges amér'),
        (N'VN', N'Viêt Nam'),
        (N'VU', N'Vanuatu'),
        (N'WF', N'Wallis & Futuna'),
        (N'WS', N'Samoa Occident.'),
        (N'YE', N'Yémen'),
        (N'YT', N'Mayotte'),
        (N'ZA', N'Afrique du Sud'),
        (N'ZM', N'Zambie'),
        (N'ZW', N'Zimbabwe')
    ) AS v(code, libelle)
)
INSERT INTO dbo.ref_pays(code, libelle, est_actif)
SELECT s.code, s.libelle, 1
FROM src s
WHERE NOT EXISTS (SELECT 1 FROM dbo.ref_pays p WHERE p.code = s.code);

PRINT N'Seed ref_pays terminé (' + CAST(@@ROWCOUNT AS NVARCHAR(10)) + N' pays insérés).';
GO
